import React,{useEffect,useState}from"react";
const API="https://script.google.com/macros/s/AKfycbzX2i0JOw5HED9JnEOEs3gwDKZgEfpvRHN1b2VS6VYlFDJVBZDrlCwCBjTEKD8EuCVipg/exec";
const flavours=[["VANILLA","CRUNCH","0%"],["GUAVA","CHILLI","25%"],["BELGIAN","CHOCOLATE","50%"],["BLUEBERRY","CHEESECAKE","75%"],["MIDNIGHT","COOKIES","100%"]];
function Count(){const[t,setT]=useState(0);useEffect(()=>{const f=()=>setT(Math.max(0,new Date("2026-10-11T00:00:00+05:30")-Date.now()));f();const i=setInterval(f,1000);return()=>clearInterval(i)},[]);const v=[Math.floor(t/864e5),Math.floor(t/36e5)%24,Math.floor(t/6e4)%60,Math.floor(t/1e3)%60];return <div className="count">{v.map((n,i)=><div><b>{String(n).padStart(2,"0")}</b><small>{["DAYS","HOURS","MIN","SEC"][i]}</small></div>)}</div>}
function Product({pos="50%"}){return <div className="product"><div className="glow"/><div className="pack" style={{backgroundPosition:pos}}/><div className="floor"/></div>}
function Signup(){const[done,setDone]=useState(false),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));try{await fetch(API,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data)});setDone(true)}catch{setBusy(false)}}return <section className="black signup"><div className="wrap signup-grid"><div><span className="eyebrow">08 / GET IN EARLY</span><h2>DON’T MISS<br/>THE CHEAT.</h2><p className="muted">Be first to know when CHEATCODE hits the market.</p></div>{done?<div className="success">✓ YOU’RE ON THE LIST.<br/><span>SEE YOU AT THE LAUNCH.</span></div>:<form onSubmit={submit}><input name="name" placeholder="YOUR NAME" required/><input name="email" type="email" placeholder="EMAIL ADDRESS" required/><input name="phone" placeholder="PHONE NUMBER" required/><button disabled={busy}>{busy?"JOINING…":"GET NOTIFIED →"}</button></form>}</div></section>}
export default function App(){return <div><header><a>CHEATCODE™</a><nav><a href="#flavours">FLAVOURS</a><a href="#story">OUR STORY</a><a href="#launch">LAUNCH</a></nav><a className="header-btn" href="#signup">GET NOTIFIED ↗</a></header><div className="ticker">YOU CAN CHEAT WITHOUT REGRET　·　10g PROTEIN　·　ZERO ADDED SUGAR　·　HIGH FIBRE　·　LAUNCHING 11.10.26　·</div><main>
<section className="hero red"><div className="wrap hero-grid"><div className="hero-copy"><span className="eyebrow">PREMIUM HIGH-PROTEIN ICE CREAM</span><h1>CHEAT<br/>WITHOUT<br/>REGRET.</h1><p className="hero-tag">Same pleasure.<br/>Better choices.</p><a className="pill" href="#signup">GET NOTIFIED <b>↗</b></a><div className="stats"><span><b>10g</b>PROTEIN</span><span><b>0</b>ADDED SUGAR</span><span><b>HIGH</b>FIBRE</span><span><b>LOW</b>CARB</span></div></div><div className="hero-product"><Product pos="50%"/><div className="side-copy">SAME<br/>PLEASURE.<br/><em>BETTER<br/>CHOICES.</em></div></div></div></section>
<section className="black flavours-sec" id="flavours"><div className="wrap"><div className="center"><span className="eyebrow redtext">OUR FLAVOURS</span><h2>5 WAYS TO CHEAT.</h2><p className="muted">Same indulgence. Different moods.</p></div><div className="flavour-row">{flavours.map((f,i)=><article><div className="mini-pack" style={{backgroundPosition:f[2]}}/><span>0{i+1}</span><h3>{f[0]}<br/>{f[1]}</h3></article>)}</div><div className="benefits">{["10g|Protein","Zero|Added Sugar","High|Fibre","Low|Carb"].map(x=>{let[a,b]=x.split("|");return <div><i>◉</i><b>{a}</b><small>{b}</small></div>})}</div></div></section>
<section className="black split"><div className="image-panel"><div className="icecream-art"/></div><div className="copy-panel"><span className="eyebrow redtext">THE BETTER INDULGENCE</span><h2>DESSERT<br/>THAT WORKS<br/>FOR YOU.</h2><p>Same creamy texture. Same rich flavours. But now with real nutrition built into the experience.</p><a className="outline" href="#story">OUR STORY ↗</a></div></section>
<section className="white story" id="story"><div className="wrap story-grid"><div><span className="eyebrow">THE CHEATCODE</span><h2>WE DIDN’T<br/>WANT TO MAKE<br/>ANOTHER<br/><span>“HEALTHY”</span><br/>ICE CREAM.</h2></div><div><p className="big">We wanted the kind of ice cream you’d actually crave.</p><p>So we built CHEATCODE for the moments when you want to indulge without feeling like you abandoned your goals.</p><strong>THAT’S THE CHEAT.</strong></div></div></section>
<section className="red launch" id="launch"><div className="wrap"><span className="eyebrow">LAUNCHING ON</span><h2>11.10.26</h2><Count/><p>NO PRE-ORDER. NO FAKE URGENCY.<br/>JUST LAUNCH DAY.</p></div><div className="launch-product"><Product pos="50%"/></div></section>
<Signup/>
<section className="black follow"><div className="wrap"><span className="eyebrow redtext">FOLLOW OUR JOURNEY</span><h2>@HOUSEOFCHEATCODE</h2><p className="muted">Behind the scenes. Flavour testing. Packaging. First batches. Launch preparation.</p><a className="outline" href="https://www.instagram.com/houseofcheatcode/">FOLLOW ON INSTAGRAM ↗</a></div></section>
<section className="red final"><div className="wrap"><span className="eyebrow">CHEATCODE™</span><h2>YOUR NEXT<br/>CHEAT IS<br/>ALMOST HERE.</h2><p>11.10.26</p></div></section></main><footer><b>CHEATCODE™</b><span>You Can Cheat Without Regret.</span><a href="mailto:hello@houseofcheatcode.com">HELLO@HOUSEOFCHEATCODE.COM</a></footer></div>}
