import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";
const URL="https://script.google.com/macros/s/AKfycbzX2i0JOw5HED9JnEOEs3gwDKZgEfpvRHN1b2VS6VYlFDJVBZDrlCwCBjTEKD8EuCVipg/exec";
const flavours=[["01","Belgian","Chocolate"],["02","Vanilla","Crunch"],["03","Blueberry","Cheesecake"],["04","Guava","Chilli"],["05","Midnight","Cookies"]];
function Count(){const [t,setT]=useState(0);useEffect(()=>{let f=()=>setT(Math.max(0,new Date("2026-10-11T00:00:00+05:30")-Date.now()));f();let i=setInterval(f,1000);return()=>clearInterval(i)},[]);let d=Math.floor(t/864e5),h=Math.floor(t%864e5/36e5),m=Math.floor(t%36e5/6e4),s=Math.floor(t%6e4/1e3),p=n=>String(n).padStart(2,"0");return <div className="count">{[[d,"DAYS"],[h,"HOURS"],[m,"MIN"],[s,"SEC"]].map(x=><div><b>{p(x[0])}</b><span>{x[1]}</span></div>)}</div>}
function Label({n,c}){return <div className="label"><span>{n} / {c}</span><i/></div>}
function Signup(){const[s,setS]=useState(false),[b,setB]=useState(false);async function go(e){e.preventDefault();setB(true);try{await fetch(URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setS(true)}catch{setB(false)}}return <section className="sec black" id="signup"><div className="wrap"><Label n="08" c="GET IN EARLY"/><h2>DON’T MISS<br/>THE CHEAT.</h2><p className="lead dim">Leave your details and be first to know when CHEATCODE hits the market.</p>{s?<div className="success">✓ YOU’RE ON THE LIST. SEE YOU AT THE LAUNCH.</div>:<form onSubmit={go}><input name="name" placeholder="NAME" required/><input name="email" type="email" placeholder="EMAIL" required/><input name="phone" placeholder="PHONE" required/><button disabled={b}>{b?"JOINING...":"JOIN THE LIST →"}</button></form>}<small>BY JOINING, YOU AGREE TO RECEIVE LAUNCH UPDATES FROM CHEATCODE™.</small></div></section>}
export default function App(){return <><header><b>CHEATCODE™</b><span>WE’RE ALMOST HERE<br/>2026</span><div>YOU CAN CHEAT WITHOUT REGRET · PREMIUM HIGH-PROTEIN ICE CREAM · LAUNCHING 11.10.26 ·</div></header><main>
<section className="sec red hero"><div className="wrap"><Label n="01" c="THE CHEATCODE"/><h1>CHEAT<br/>CODE<sup>™</sup></h1><p className="tag">You Can Cheat Without Regret.</p><p className="pills">10g Protein　•　Zero Added Sugar　•　High Fibre</p><strong>11.10.26</strong></div></section>
<section className="sec black"><div className="wrap"><Label n="02" c="WHAT IS CHEATCODE?"/><div className="grid"><h2>ICE CREAM,<br/>BUT WITH A<br/>CHEATCODE.</h2><div><p className="lead">Real ice cream experience. More protein. Zero added sugar.</p><p className="dim">Made for people who don’t want to compromise on taste or what they put in their body.</p><div className="stats"><b>10g<br/><small>PROTEIN</small></b><b>0<br/><small>ADDED SUGAR</small></b><b>+<br/><small>HIGH FIBRE</small></b></div></div></div></div></section>
<section className="sec white"><div className="wrap"><Label n="03" c="THE DIFFERENCE"/><div className="grid"><h2>YOU WANT<br/>ICE CREAM.<br/>WE GET IT.</h2><div><p className="lead">Creamy texture. Indulgence. Flavour.</p><p>But also: <b>MORE PROTEIN.</b> <b>ZERO ADDED SUGAR.</b> Less compromise.</p><h3>SO WE MADE<br/>THE CHEATCODE.</h3></div></div></div></section>
<section className="sec red"><div className="wrap"><Label n="04" c="MEET THE CHEATS"/><h2>5 FLAVOURS.<br/>1 SERIOUS CHEAT.</h2><div className="flavours">{flavours.map(f=><article><span>{f[0]}</span><h3>{f[1]}<br/>{f[2]}</h3></article>)}</div></div></section>
<section className="sec black"><div className="wrap"><Label n="05" c="WHY CHEATCODE?"/><h2>BECAUSE<br/>“HEALTHY”<br/>SHOULDN’T<br/>MEAN BORING.</h2><div className="principles">{["Premium Ingredients.","Big Flavour.","Protein Packed.","Zero Added Sugar."].map(x=><article><h3>{x}</h3><p className="dim">Built for a premium ice cream experience without the usual compromise.</p></article>)}</div></div></section>
<section className="sec white"><div className="wrap"><Label n="06" c="THE STORY"/><div className="story">WE DIDN’T WANT TO MAKE ANOTHER “HEALTHY” ICE CREAM.</div><div className="grid"><span className="quote">“</span><div><p className="lead">We wanted the kind of ice cream you’d actually crave.</p><p>Built CHEATCODE for moments when you want to indulge without feeling like you abandoned your goals.</p><h3>THAT’S<br/>THE CHEAT.</h3></div></div></div></section>
<section className="sec red"><div className="wrap"><Label n="07" c="LIVE COUNTDOWN"/><h2>THE CHEAT<br/>IS COMING.</h2><Count/><p className="note">11 • 10 • 26<br/><br/>NO PRE-ORDER. NO FAKE URGENCY. JUST LAUNCH DAY.</p></div></section>
<Signup/>
<section className="sec white"><div className="wrap"><Label n="09" c="FOLLOW THE BUILD"/><div className="grid"><h2>WATCH US<br/>BUILD THE<br/>CHEATCODE.</h2><div><p className="lead">Behind the scenes. Flavour testing. Packaging. First batches. Launch preparation.</p><a href="https://www.instagram.com/houseofcheatcode/">FOLLOW US ON INSTAGRAM ↗</a></div></div></div></section>
<section className="sec red final"><div className="wrap"><Label n="10" c="FINAL CALL"/><h1>YOUR NEXT<br/>CHEAT IS<br/>ALMOST HERE.</h1><p>CHEATCODE™　·　11.10.26</p></div></section></main><footer>© 2026 CHEATCODE™ <a href="mailto:hello@houseofcheatcode.com">HELLO@HOUSEOFCHEATCODE.COM</a></footer></>}
